### ISSUE TITLE
Feature Request: See which AP you are connected to

### ISSUE THREAD

**Issue by metageektrent** [metageek-llc/inSSIDer-2#12]
a feature that enables you to see which ap the wireless card is currently communicating with.

from: http://www.metageek.net/forums/showthread.php?3559-Feature-to-see-which-AP-you-are-connected-to

**Comment by TylerAdkisson** [comment]
I have it working on both NDIS(WinXP) and ManagedWiFi(Vista & 7) in my fork, so you can probably close this issue.

**Comment by metageektrent** [comment]
Okay.
