### ISSUE TITLE
MissingMethodException in NetworkScanner.ScanThreadFunc()

### ISSUE THREAD

**Issue by ryanwoodings** [metageek-llc/inSSIDer-2#14]
[Message]
Methode nicht gefunden: Int32 System.Threading.WaitHandle.WaitAny(System.Threading.WaitHandle[], Int32).

[Version]
2.0.2.1005

[WinVer]
Microsoft Windows NT 5.1.2600 Service Pack 3

[Platform]
x86

[StackTrace]
System.MissingMethodException: Methode nicht gefunden: Int32 System.Threading.WaitHandle.WaitAny(System.Threading.WaitHandle[], Int32).
bei inSSIDer.Scanning.NetworkScanner.ScanThreadFunc()
bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
bei System.Threading.ThreadHelper.ThreadStart()

**Comment by TylerAdkisson** [comment]
I _think_ this is safe to close.

**Comment by junkshow** [comment]
http://blogs.msdn.com/b/msbuild/archive/2007/10/09/multitargeting-against-net-2-0.aspx.  Apparently still a problem even with VS2010 builds, as I just saw an error report for this from InSSIDer 2.1.0.  I've attempted to catch it and display a helpful dialog.
